"""
Deterministic financial-metric extraction from parsed filing tables.

Numbers are never generated by the LLM. `extract_metric_from_tables` does
pure keyword/regex matching over structured table rows; the LLM is only
used (via `LabelLearner`) as a one-time fallback to classify a row label
when no static keyword matches — and that result is cached permanently.
"""

import json
import re

from .llm_utils import extract_text, invoke_with_retry


def extract_metric_from_tables(parsed: dict, keywords: list) -> dict:
    """
    Saare filings ke tables mein se wo rows dhoondhta hai jinka label
    keyword se match kare (jaise "revenue", "cost of revenue").
    Numbers ko clean karke float mein convert karta hai
    (parentheses = negative, $ aur commas hata deta hai).
    """
    results = {}
    for doc_name, data in parsed.items():
        for table_idx, table in enumerate(data["tables"]):
            for row in table:
                if not row:
                    continue
                label = row[0].lower()
                if any(kw in label for kw in keywords):
                    numbers = []
                    for cell in row[1:]:
                        cleaned = re.sub(r"[^\d\.\-\(\)]", "", cell)
                        if cleaned in ("", "-", "."):
                            continue
                        is_negative = cleaned.startswith("(") and cleaned.endswith(")")
                        cleaned = cleaned.strip("()")
                        try:
                            val = float(cleaned)
                            if is_negative:
                                val = -val
                            numbers.append(val)
                        except ValueError:
                            continue
                    if numbers:
                        results.setdefault(doc_name, []).append({
                            "label": row[0],
                            "values": numbers,
                            "table_idx": table_idx,
                        })
    return results


def classify_labels_with_llm(llm, data: dict, company: str, metric_type: str, stats=None):
    """
    Poore document (saari tables) ke row-labels EK HI LLM call mein dikhata hai
    (table-by-table nahi — 10-K mein income statement document ke bahut peeche
    ho sakti hai, isliye pehli N tables tak limit karna miss kar sakta hai).
    """
    candidates = []
    seen = set()
    for table_idx, table in enumerate(data["tables"]):
        for row in table:
            if not row or not row[0].strip():
                continue
            label = row[0].strip()
            key = (table_idx, label.lower())
            if key in seen:
                continue
            seen.add(key)
            sample_values = row[1:3] if len(row) > 1 else []
            candidates.append(f"[table {table_idx}] {label} | {sample_values}")

    if not candidates:
        return None

    candidates = candidates[:500]  # prompt size cap — bahut badi filings ke liye
    context = "\n".join(candidates)

    metric_desc = (
        "total revenue / net sales (top-line income)" if metric_type == "revenue"
        else "cost of revenue / cost of goods sold (direct cost of producing the revenue)"
    )

    prompt = f"""Yahan {company} ke ek SEC filing ke tables ke rows hain (format: [table N] label | sample values):
{context}

Inme se kaunsa row label "{metric_desc}" represent karta hai? Sirf income statement
(consolidated statement of earnings/operations) wali row consider karo, koi
segment-breakdown ya percentage-of-sales row nahi.

Reply ONLY valid JSON, kuch aur text nahi: {{"label": "<exact label as shown>"}}
Agar koi match nahi milta: {{"label": null}}"""

    response = invoke_with_retry(llm, prompt, stats=stats)
    text = extract_text(response).strip()
    text = re.sub(r"^```(json)?|```$", "", text.strip(), flags=re.MULTILINE).strip()

    try:
        parsed_json = json.loads(text)
        label = parsed_json.get("label")
    except (json.JSONDecodeError, AttributeError):
        return None

    if not label:
        return None
    return label.strip().lower()


class LabelLearner:
    """
    Holds the runtime-learned keyword lists and the LLM-classification cache.
    Instantiate once per pipeline run (or per process) and reuse across calls —
    that's what makes the LLM fallback a one-time cost per (doc, metric_type)
    rather than a repeated one.
    """

    def __init__(self):
        self.learned_keywords = {"revenue": [], "cost": []}
        self._cache = {}  # (doc_name, metric_type) -> bool (found or not)

    def extract_with_fallback(self, llm, parsed: dict, base_keywords: list,
                               metric_type: str, company: str, stats=None) -> dict:
        """
        Pehle static keyword-matching try karta hai (fast, free). Agar kisi filing
        ke liye kuch match hi nahi hota, LLM se poore doc ke labels classify
        karwata hai (ek hi call mein) aur naya label learned_keywords mein
        permanently add kar deta hai — taaki agli baar LLM call na lagni pade.
        """
        keywords = base_keywords + self.learned_keywords[metric_type]
        results = extract_metric_from_tables(parsed, keywords)

        for doc_name, data in parsed.items():
            if doc_name in results:
                continue

            cache_key = (doc_name, metric_type)
            if cache_key in self._cache:
                continue

            classified_label = classify_labels_with_llm(llm, data, company, metric_type, stats=stats)
            if classified_label and classified_label not in self.learned_keywords[metric_type]:
                print(f"LLM-learned {metric_type} keyword: '{classified_label}' (from {doc_name})")
                self.learned_keywords[metric_type].append(classified_label)
                keywords = base_keywords + self.learned_keywords[metric_type]
                results = extract_metric_from_tables(parsed, keywords)
                self._cache[cache_key] = True
            else:
                self._cache[cache_key] = False
                print(f"LLM could not classify {metric_type} for {doc_name}")

        return results


def calc_growth_rate(old, new):
    if old == 0 or old is None:
        return None
    return round((new - old) / abs(old) * 100, 2)


def calc_cagr(begin_value, end_value, years):
    if begin_value <= 0 or years <= 0:
        return None
    return round(((end_value / begin_value) ** (1 / years) - 1) * 100, 2)


def calc_margin(revenue, cost):
    if revenue == 0 or revenue is None:
        return None
    return round((revenue - cost) / revenue * 100, 2)
